services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./back:/var/www/laravel
    depends_on:
      - mysql
      - php
  php:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./back:/var/www/laravel
  mysql:
    image: mysql:8.0
    ports:
      - "8003:3306"
    env_file:
      - env/mysql.env
    volumes:
      - db_data:/var/lib/mysql
  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - db_data:/var/www/laravel
  artisan:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./back:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
  client:
    build:
      context: front
      dockerfile: ../docker/node.Dockerfile
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
      - ./front/package.json:/app/package.json
      - ./front/yarn.lock:/app/yarn.lock
      - /front/node_modules
    ports:
      - "8002:5173"
volumes:
  db_data: